# Generated by Django 3.2.4 on 2023-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('class_name', models.CharField(help_text='Eg- Third, Fouth,Sixth etc', max_length=100, primary_key=True, serialize=False)),
                ('section', models.CharField(help_text='Eg- A,B,C etc', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('class_name', 'section')},
            },
        ),
    ]
