# Generated by Django 5.0.3 on 2024-08-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_adhaar_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhaar',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Aadhar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
