# Generated by Django 5.0.3 on 2024-08-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission_form',
            table=None,
        ),
    ]
